### ISSUE TITLE
Upgrade to imgui 0.2.1

### ISSUE THREAD

**Issue by fkarg** [germangb/imgui-ext#16]
Hey,

this seems to be pretty awesome and I'd love to use it. However I am bound to imgui 0.2.1^ for my project, and manually upgrading resulted in 1458 errors. Not-Upgrading resulted in one error about a version mismatch between the imgui::Ui struct versions.

**Comment by germangb** [comment]
I will take a look at it tomorrow.

**Comment by germangb** [comment]
I've upgraded the dependency to imgui 0.2 in the master branch. I still need to fix the doc tests before publishing the crate. In the meantime you can use the latest commit

**Comment by fkarg** [comment]
awesome, thank you very much!

**Comment by germangb** [comment]
Closing to continue in #23
